version: '3.1'

services:
  db:
    image: mariadb:10.11
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    
  api:
    build: .
    ports:
      - "8000:8000"

volumes:
  db_data:
